# Auto-generated all-label capture commands
# Generated from reference_capture_checklist.csv
# Run from examples/BachelorsProject

# 1. fighting_stance__front
& "python" "action_recognition.py" --weights "yolo26n-pose.pt" --source "https://www.youtube.com/watch?v=SjLXzCpRS8U" --record-reference "fighting_stance__front" --target-technique "fighting_stance" --reference-dir "reference_poses" --num-video-sequence-samples 12 --skip-frame 1 --save-kpts-dir "keypoints" --record-reference-max-saves 1 --reference-capture-cooldown-frames 24 --disable-video-classifier --visualize-pose --auto-exit-after-reference --reference-search-max-frames 1800 --person-selection-mode "most_motion" --disable-structured-storage --reference-capture-mode "best_window" --ref-min-motion-energy 0.02 --ref-min-score-gate 0

# 2. fighting_stance__left45
& "python" "action_recognition.py" --weights "yolo26n-pose.pt" --source "https://www.youtube.com/watch?v=e2S6-gwR0es" --record-reference "fighting_stance__left45" --target-technique "fighting_stance" --reference-dir "reference_poses" --num-video-sequence-samples 12 --skip-frame 1 --save-kpts-dir "keypoints" --record-reference-max-saves 1 --reference-capture-cooldown-frames 24 --disable-video-classifier --visualize-pose --auto-exit-after-reference --reference-search-max-frames 1800 --person-selection-mode "most_motion" --disable-structured-storage --reference-capture-mode "best_window" --ref-min-motion-energy 0.02 --ref-min-score-gate 0

# 3. fighting_stance__right45
& "python" "action_recognition.py" --weights "yolo26n-pose.pt" --source "https://www.youtube.com/watch?v=pFlW2MtfIVs" --record-reference "fighting_stance__right45" --target-technique "fighting_stance" --reference-dir "reference_poses" --num-video-sequence-samples 12 --skip-frame 1 --save-kpts-dir "keypoints" --record-reference-max-saves 1 --reference-capture-cooldown-frames 24 --disable-video-classifier --visualize-pose --auto-exit-after-reference --reference-search-max-frames 1800 --person-selection-mode "most_motion" --disable-structured-storage --reference-capture-mode "best_window" --ref-min-motion-energy 0.02 --ref-min-score-gate 0

# 4. fighting_stance__side
& "python" "action_recognition.py" --weights "yolo26n-pose.pt" --source "https://www.youtube.com/watch?v=75KjoTO1dJs" --record-reference "fighting_stance__side" --target-technique "fighting_stance" --reference-dir "reference_poses" --num-video-sequence-samples 12 --skip-frame 1 --save-kpts-dir "keypoints" --record-reference-max-saves 1 --reference-capture-cooldown-frames 24 --disable-video-classifier --visualize-pose --auto-exit-after-reference --reference-search-max-frames 1800 --person-selection-mode "most_motion" --disable-structured-storage --reference-capture-mode "best_window" --ref-min-motion-energy 0.02 --ref-min-score-gate 0

# 5. jab__front
& "python" "action_recognition.py" --weights "yolo26n-pose.pt" --source "https://www.youtube.com/watch?v=71nmi6nGcrY" --record-reference "jab__front" --target-technique "jab" --reference-dir "reference_poses" --num-video-sequence-samples 12 --skip-frame 1 --save-kpts-dir "keypoints" --record-reference-max-saves 1 --reference-capture-cooldown-frames 24 --disable-video-classifier --visualize-pose --auto-exit-after-reference --reference-search-max-frames 1800 --person-selection-mode "most_motion" --disable-structured-storage --reference-capture-mode "best_window" --ref-min-motion-energy 0.02 --ref-min-score-gate 0

# 6. jab__left45
& "python" "action_recognition.py" --weights "yolo26n-pose.pt" --source "https://www.youtube.com/watch?v=hNclexRmDsY" --record-reference "jab__left45" --target-technique "jab" --reference-dir "reference_poses" --num-video-sequence-samples 12 --skip-frame 1 --save-kpts-dir "keypoints" --record-reference-max-saves 1 --reference-capture-cooldown-frames 24 --disable-video-classifier --visualize-pose --auto-exit-after-reference --reference-search-max-frames 1800 --person-selection-mode "most_motion" --disable-structured-storage --reference-capture-mode "best_window" --ref-min-motion-energy 0.02 --ref-min-score-gate 0

# 7. jab__right45
& "python" "action_recognition.py" --weights "yolo26n-pose.pt" --source "https://www.youtube.com/watch?v=h4vQrtKr5F0" --record-reference "jab__right45" --target-technique "jab" --reference-dir "reference_poses" --num-video-sequence-samples 12 --skip-frame 1 --save-kpts-dir "keypoints" --record-reference-max-saves 1 --reference-capture-cooldown-frames 24 --disable-video-classifier --visualize-pose --auto-exit-after-reference --reference-search-max-frames 1800 --person-selection-mode "most_motion" --disable-structured-storage --reference-capture-mode "best_window" --ref-min-motion-energy 0.02 --ref-min-score-gate 0

# 8. jab__side
& "python" "action_recognition.py" --weights "yolo26n-pose.pt" --source "https://www.youtube.com/watch?v=n-PBmzmeXSI" --record-reference "jab__side" --target-technique "jab" --reference-dir "reference_poses" --num-video-sequence-samples 12 --skip-frame 1 --save-kpts-dir "keypoints" --record-reference-max-saves 1 --reference-capture-cooldown-frames 24 --disable-video-classifier --visualize-pose --auto-exit-after-reference --reference-search-max-frames 1800 --person-selection-mode "most_motion" --disable-structured-storage --reference-capture-mode "best_window" --ref-min-motion-energy 0.02 --ref-min-score-gate 0

# 9. cross__front
& "python" "action_recognition.py" --weights "yolo26n-pose.pt" --source "https://www.youtube.com/watch?v=sK-6Ujp3KYY" --record-reference "cross__front" --target-technique "cross" --reference-dir "reference_poses" --num-video-sequence-samples 12 --skip-frame 1 --save-kpts-dir "keypoints" --record-reference-max-saves 1 --reference-capture-cooldown-frames 24 --disable-video-classifier --visualize-pose --auto-exit-after-reference --reference-search-max-frames 1800 --person-selection-mode "most_motion" --disable-structured-storage --reference-capture-mode "best_window" --ref-min-motion-energy 0.02 --ref-min-score-gate 0

# 10. cross__left45
& "python" "action_recognition.py" --weights "yolo26n-pose.pt" --source "https://www.youtube.com/watch?v=ce-lVnoUYTs" --record-reference "cross__left45" --target-technique "cross" --reference-dir "reference_poses" --num-video-sequence-samples 12 --skip-frame 1 --save-kpts-dir "keypoints" --record-reference-max-saves 1 --reference-capture-cooldown-frames 24 --disable-video-classifier --visualize-pose --auto-exit-after-reference --reference-search-max-frames 1800 --person-selection-mode "most_motion" --disable-structured-storage --reference-capture-mode "best_window" --ref-min-motion-energy 0.02 --ref-min-score-gate 0

# 11. cross__right45
& "python" "action_recognition.py" --weights "yolo26n-pose.pt" --source "https://www.youtube.com/watch?v=wxZjcfMDZvw" --record-reference "cross__right45" --target-technique "cross" --reference-dir "reference_poses" --num-video-sequence-samples 12 --skip-frame 1 --save-kpts-dir "keypoints" --record-reference-max-saves 1 --reference-capture-cooldown-frames 24 --disable-video-classifier --visualize-pose --auto-exit-after-reference --reference-search-max-frames 1800 --person-selection-mode "most_motion" --disable-structured-storage --reference-capture-mode "best_window" --ref-min-motion-energy 0.02 --ref-min-score-gate 0

# 12. cross__side
& "python" "action_recognition.py" --weights "yolo26n-pose.pt" --source "https://www.youtube.com/watch?v=JhkqSCahsNY" --record-reference "cross__side" --target-technique "cross" --reference-dir "reference_poses" --num-video-sequence-samples 12 --skip-frame 1 --save-kpts-dir "keypoints" --record-reference-max-saves 1 --reference-capture-cooldown-frames 24 --disable-video-classifier --visualize-pose --auto-exit-after-reference --reference-search-max-frames 1800 --person-selection-mode "most_motion" --disable-structured-storage --reference-capture-mode "best_window" --ref-min-motion-energy 0.02 --ref-min-score-gate 0

# 13. hook__front
& "python" "action_recognition.py" --weights "yolo26n-pose.pt" --source "https://www.youtube.com/watch?v=MJmHnyBjC6s" --record-reference "hook__front" --target-technique "hook" --reference-dir "reference_poses" --num-video-sequence-samples 12 --skip-frame 1 --save-kpts-dir "keypoints" --record-reference-max-saves 1 --reference-capture-cooldown-frames 24 --disable-video-classifier --visualize-pose --auto-exit-after-reference --reference-search-max-frames 1800 --person-selection-mode "most_motion" --disable-structured-storage --reference-capture-mode "best_window" --ref-min-motion-energy 0.02 --ref-min-score-gate 0

# 14. hook__left45
& "python" "action_recognition.py" --weights "yolo26n-pose.pt" --source "https://www.youtube.com/watch?v=hAOIr4G_QQk" --record-reference "hook__left45" --target-technique "hook" --reference-dir "reference_poses" --num-video-sequence-samples 12 --skip-frame 1 --save-kpts-dir "keypoints" --record-reference-max-saves 1 --reference-capture-cooldown-frames 24 --disable-video-classifier --visualize-pose --auto-exit-after-reference --reference-search-max-frames 1800 --person-selection-mode "most_motion" --disable-structured-storage --reference-capture-mode "best_window" --ref-min-motion-energy 0.02 --ref-min-score-gate 0

# 15. hook__right45
& "python" "action_recognition.py" --weights "yolo26n-pose.pt" --source "https://www.youtube.com/watch?v=ce-lVnoUYTs" --record-reference "hook__right45" --target-technique "hook" --reference-dir "reference_poses" --num-video-sequence-samples 12 --skip-frame 1 --save-kpts-dir "keypoints" --record-reference-max-saves 1 --reference-capture-cooldown-frames 24 --disable-video-classifier --visualize-pose --auto-exit-after-reference --reference-search-max-frames 1800 --person-selection-mode "most_motion" --disable-structured-storage --reference-capture-mode "best_window" --ref-min-motion-energy 0.02 --ref-min-score-gate 0

# 16. hook__side
& "python" "action_recognition.py" --weights "yolo26n-pose.pt" --source "https://www.youtube.com/watch?v=0gtMKaCJ5I8" --record-reference "hook__side" --target-technique "hook" --reference-dir "reference_poses" --num-video-sequence-samples 12 --skip-frame 1 --save-kpts-dir "keypoints" --record-reference-max-saves 1 --reference-capture-cooldown-frames 24 --disable-video-classifier --visualize-pose --auto-exit-after-reference --reference-search-max-frames 1800 --person-selection-mode "most_motion" --disable-structured-storage --reference-capture-mode "best_window" --ref-min-motion-energy 0.02 --ref-min-score-gate 0

# 17. uppercut__front
& "python" "action_recognition.py" --weights "yolo26n-pose.pt" --source "https://www.youtube.com/watch?v=eBxn21FtqPg" --record-reference "uppercut__front" --target-technique "uppercut" --reference-dir "reference_poses" --num-video-sequence-samples 12 --skip-frame 1 --save-kpts-dir "keypoints" --record-reference-max-saves 1 --reference-capture-cooldown-frames 24 --disable-video-classifier --visualize-pose --auto-exit-after-reference --reference-search-max-frames 1800 --person-selection-mode "most_motion" --disable-structured-storage --reference-capture-mode "best_window" --ref-min-motion-energy 0.02 --ref-min-score-gate 0

# 18. uppercut__left45
& "python" "action_recognition.py" --weights "yolo26n-pose.pt" --source "https://www.youtube.com/watch?v=GxMOV3ibhWg" --record-reference "uppercut__left45" --target-technique "uppercut" --reference-dir "reference_poses" --num-video-sequence-samples 12 --skip-frame 1 --save-kpts-dir "keypoints" --record-reference-max-saves 1 --reference-capture-cooldown-frames 24 --disable-video-classifier --visualize-pose --auto-exit-after-reference --reference-search-max-frames 1800 --person-selection-mode "most_motion" --disable-structured-storage --reference-capture-mode "best_window" --ref-min-motion-energy 0.02 --ref-min-score-gate 0

# 19. uppercut__right45
& "python" "action_recognition.py" --weights "yolo26n-pose.pt" --source "https://www.youtube.com/watch?v=GxMOV3ibhWg" --record-reference "uppercut__right45" --target-technique "uppercut" --reference-dir "reference_poses" --num-video-sequence-samples 12 --skip-frame 1 --save-kpts-dir "keypoints" --record-reference-max-saves 1 --reference-capture-cooldown-frames 24 --disable-video-classifier --visualize-pose --auto-exit-after-reference --reference-search-max-frames 1800 --person-selection-mode "most_motion" --disable-structured-storage --reference-capture-mode "best_window" --ref-min-motion-energy 0.02 --ref-min-score-gate 0

# 20. uppercut__side
& "python" "action_recognition.py" --weights "yolo26n-pose.pt" --source "https://www.youtube.com/watch?v=meUNR0SgSXw" --record-reference "uppercut__side" --target-technique "uppercut" --reference-dir "reference_poses" --num-video-sequence-samples 12 --skip-frame 1 --save-kpts-dir "keypoints" --record-reference-max-saves 1 --reference-capture-cooldown-frames 24 --disable-video-classifier --visualize-pose --auto-exit-after-reference --reference-search-max-frames 1800 --person-selection-mode "most_motion" --disable-structured-storage --reference-capture-mode "best_window" --ref-min-motion-energy 0.02 --ref-min-score-gate 0

# 21. front_kick__front
& "python" "action_recognition.py" --weights "yolo26n-pose.pt" --source "https://www.youtube.com/watch?v=eg7LpOr5yzY" --record-reference "front_kick__front" --target-technique "front_kick" --reference-dir "reference_poses" --num-video-sequence-samples 12 --skip-frame 1 --save-kpts-dir "keypoints" --record-reference-max-saves 1 --reference-capture-cooldown-frames 24 --disable-video-classifier --visualize-pose --auto-exit-after-reference --reference-search-max-frames 1800 --person-selection-mode "most_motion" --disable-structured-storage --reference-capture-mode "best_window" --ref-min-motion-energy 0.02 --ref-min-score-gate 0

# 22. front_kick__left45
& "python" "action_recognition.py" --weights "yolo26n-pose.pt" --source "https://www.youtube.com/watch?v=me9y-Uz6otg" --record-reference "front_kick__left45" --target-technique "front_kick" --reference-dir "reference_poses" --num-video-sequence-samples 12 --skip-frame 1 --save-kpts-dir "keypoints" --record-reference-max-saves 1 --reference-capture-cooldown-frames 24 --disable-video-classifier --visualize-pose --auto-exit-after-reference --reference-search-max-frames 1800 --person-selection-mode "most_motion" --disable-structured-storage --reference-capture-mode "best_window" --ref-min-motion-energy 0.02 --ref-min-score-gate 0

# 23. front_kick__right45
& "python" "action_recognition.py" --weights "yolo26n-pose.pt" --source "https://www.youtube.com/watch?v=CO4S2daMICk" --record-reference "front_kick__right45" --target-technique "front_kick" --reference-dir "reference_poses" --num-video-sequence-samples 12 --skip-frame 1 --save-kpts-dir "keypoints" --record-reference-max-saves 1 --reference-capture-cooldown-frames 24 --disable-video-classifier --visualize-pose --auto-exit-after-reference --reference-search-max-frames 1800 --person-selection-mode "most_motion" --disable-structured-storage --reference-capture-mode "best_window" --ref-min-motion-energy 0.02 --ref-min-score-gate 0

# 24. front_kick__side
& "python" "action_recognition.py" --weights "yolo26n-pose.pt" --source "https://www.youtube.com/watch?v=aWjz5NgzhTw" --record-reference "front_kick__side" --target-technique "front_kick" --reference-dir "reference_poses" --num-video-sequence-samples 12 --skip-frame 1 --save-kpts-dir "keypoints" --record-reference-max-saves 1 --reference-capture-cooldown-frames 24 --disable-video-classifier --visualize-pose --auto-exit-after-reference --reference-search-max-frames 1800 --person-selection-mode "most_motion" --disable-structured-storage --reference-capture-mode "best_window" --ref-min-motion-energy 0.02 --ref-min-score-gate 0

# 25. roundhouse_kick__front
& "python" "action_recognition.py" --weights "yolo26n-pose.pt" --source "https://www.youtube.com/watch?v=BEYGp-npoHc" --record-reference "roundhouse_kick__front" --target-technique "roundhouse_kick" --reference-dir "reference_poses" --num-video-sequence-samples 12 --skip-frame 1 --save-kpts-dir "keypoints" --record-reference-max-saves 1 --reference-capture-cooldown-frames 24 --disable-video-classifier --visualize-pose --auto-exit-after-reference --reference-search-max-frames 1800 --person-selection-mode "most_motion" --disable-structured-storage --reference-capture-mode "best_window" --ref-min-motion-energy 0.02 --ref-min-score-gate 0

# 26. roundhouse_kick__left45
& "python" "action_recognition.py" --weights "yolo26n-pose.pt" --source "https://www.youtube.com/watch?v=Bp_QVO7kYtg" --record-reference "roundhouse_kick__left45" --target-technique "roundhouse_kick" --reference-dir "reference_poses" --num-video-sequence-samples 12 --skip-frame 1 --save-kpts-dir "keypoints" --record-reference-max-saves 1 --reference-capture-cooldown-frames 24 --disable-video-classifier --visualize-pose --auto-exit-after-reference --reference-search-max-frames 1800 --person-selection-mode "most_motion" --disable-structured-storage --reference-capture-mode "best_window" --ref-min-motion-energy 0.02 --ref-min-score-gate 0

# 27. roundhouse_kick__right45
& "python" "action_recognition.py" --weights "yolo26n-pose.pt" --source "https://www.youtube.com/watch?v=eQFo1L9g4Sc" --record-reference "roundhouse_kick__right45" --target-technique "roundhouse_kick" --reference-dir "reference_poses" --num-video-sequence-samples 12 --skip-frame 1 --save-kpts-dir "keypoints" --record-reference-max-saves 1 --reference-capture-cooldown-frames 24 --disable-video-classifier --visualize-pose --auto-exit-after-reference --reference-search-max-frames 1800 --person-selection-mode "most_motion" --disable-structured-storage --reference-capture-mode "best_window" --ref-min-motion-energy 0.02 --ref-min-score-gate 0

# 28. roundhouse_kick__side
& "python" "action_recognition.py" --weights "yolo26n-pose.pt" --source "https://www.youtube.com/watch?v=KrR-58vvMnY" --record-reference "roundhouse_kick__side" --target-technique "roundhouse_kick" --reference-dir "reference_poses" --num-video-sequence-samples 12 --skip-frame 1 --save-kpts-dir "keypoints" --record-reference-max-saves 1 --reference-capture-cooldown-frames 24 --disable-video-classifier --visualize-pose --auto-exit-after-reference --reference-search-max-frames 1800 --person-selection-mode "most_motion" --disable-structured-storage --reference-capture-mode "best_window" --ref-min-motion-energy 0.02 --ref-min-score-gate 0

# 29. side_kick__front
& "python" "action_recognition.py" --weights "yolo26n-pose.pt" --source "https://www.youtube.com/watch?v=8ZzAEfRlB_s" --record-reference "side_kick__front" --target-technique "side_kick" --reference-dir "reference_poses" --num-video-sequence-samples 12 --skip-frame 1 --save-kpts-dir "keypoints" --record-reference-max-saves 1 --reference-capture-cooldown-frames 24 --disable-video-classifier --visualize-pose --auto-exit-after-reference --reference-search-max-frames 1800 --person-selection-mode "most_motion" --disable-structured-storage --reference-capture-mode "best_window" --ref-min-motion-energy 0.02 --ref-min-score-gate 0

# 30. side_kick__left45
& "python" "action_recognition.py" --weights "yolo26n-pose.pt" --source "https://www.youtube.com/watch?v=gih8JPD-9KU" --record-reference "side_kick__left45" --target-technique "side_kick" --reference-dir "reference_poses" --num-video-sequence-samples 12 --skip-frame 1 --save-kpts-dir "keypoints" --record-reference-max-saves 1 --reference-capture-cooldown-frames 24 --disable-video-classifier --visualize-pose --auto-exit-after-reference --reference-search-max-frames 1800 --person-selection-mode "most_motion" --disable-structured-storage --reference-capture-mode "best_window" --ref-min-motion-energy 0.02 --ref-min-score-gate 0

# 31. side_kick__right45
& "python" "action_recognition.py" --weights "yolo26n-pose.pt" --source "https://www.youtube.com/watch?v=f-0cCiOIJn4" --record-reference "side_kick__right45" --target-technique "side_kick" --reference-dir "reference_poses" --num-video-sequence-samples 12 --skip-frame 1 --save-kpts-dir "keypoints" --record-reference-max-saves 1 --reference-capture-cooldown-frames 24 --disable-video-classifier --visualize-pose --auto-exit-after-reference --reference-search-max-frames 1800 --person-selection-mode "most_motion" --disable-structured-storage --reference-capture-mode "best_window" --ref-min-motion-energy 0.02 --ref-min-score-gate 0

# 32. side_kick__side
& "python" "action_recognition.py" --weights "yolo26n-pose.pt" --source "https://www.youtube.com/watch?v=2H0qIAH-T6M" --record-reference "side_kick__side" --target-technique "side_kick" --reference-dir "reference_poses" --num-video-sequence-samples 12 --skip-frame 1 --save-kpts-dir "keypoints" --record-reference-max-saves 1 --reference-capture-cooldown-frames 24 --disable-video-classifier --visualize-pose --auto-exit-after-reference --reference-search-max-frames 1800 --person-selection-mode "most_motion" --disable-structured-storage --reference-capture-mode "best_window" --ref-min-motion-energy 0.02 --ref-min-score-gate 0

# 33. back_kick__front
& "python" "action_recognition.py" --weights "yolo26n-pose.pt" --source "https://www.youtube.com/watch?v=5pSKO3LiItU" --record-reference "back_kick__front" --target-technique "back_kick" --reference-dir "reference_poses" --num-video-sequence-samples 12 --skip-frame 1 --save-kpts-dir "keypoints" --record-reference-max-saves 1 --reference-capture-cooldown-frames 24 --disable-video-classifier --visualize-pose --auto-exit-after-reference --reference-search-max-frames 1800 --person-selection-mode "most_motion" --disable-structured-storage --reference-capture-mode "best_window" --ref-min-motion-energy 0.02 --ref-min-score-gate 0

# 34. back_kick__left45
& "python" "action_recognition.py" --weights "yolo26n-pose.pt" --source "https://www.youtube.com/watch?v=aV0QCW4vf1g" --record-reference "back_kick__left45" --target-technique "back_kick" --reference-dir "reference_poses" --num-video-sequence-samples 12 --skip-frame 1 --save-kpts-dir "keypoints" --record-reference-max-saves 1 --reference-capture-cooldown-frames 24 --disable-video-classifier --visualize-pose --auto-exit-after-reference --reference-search-max-frames 1800 --person-selection-mode "most_motion" --disable-structured-storage --reference-capture-mode "best_window" --ref-min-motion-energy 0.02 --ref-min-score-gate 0

# 35. back_kick__right45
& "python" "action_recognition.py" --weights "yolo26n-pose.pt" --source "https://www.youtube.com/watch?v=LqHUf0H6bb4" --record-reference "back_kick__right45" --target-technique "back_kick" --reference-dir "reference_poses" --num-video-sequence-samples 12 --skip-frame 1 --save-kpts-dir "keypoints" --record-reference-max-saves 1 --reference-capture-cooldown-frames 24 --disable-video-classifier --visualize-pose --auto-exit-after-reference --reference-search-max-frames 1800 --person-selection-mode "most_motion" --disable-structured-storage --reference-capture-mode "best_window" --ref-min-motion-energy 0.02 --ref-min-score-gate 0

# 36. back_kick__side
& "python" "action_recognition.py" --weights "yolo26n-pose.pt" --source "https://www.youtube.com/watch?v=a7LsNhMOlMc" --record-reference "back_kick__side" --target-technique "back_kick" --reference-dir "reference_poses" --num-video-sequence-samples 12 --skip-frame 1 --save-kpts-dir "keypoints" --record-reference-max-saves 1 --reference-capture-cooldown-frames 24 --disable-video-classifier --visualize-pose --auto-exit-after-reference --reference-search-max-frames 1800 --person-selection-mode "most_motion" --disable-structured-storage --reference-capture-mode "best_window" --ref-min-motion-energy 0.02 --ref-min-score-gate 0

# 37. spinning_back_kick__front
& "python" "action_recognition.py" --weights "yolo26n-pose.pt" --source "https://www.youtube.com/watch?v=81PkDXrPqFI" --record-reference "spinning_back_kick__front" --target-technique "spinning_back_kick" --reference-dir "reference_poses" --num-video-sequence-samples 12 --skip-frame 1 --save-kpts-dir "keypoints" --record-reference-max-saves 1 --reference-capture-cooldown-frames 24 --disable-video-classifier --visualize-pose --auto-exit-after-reference --reference-search-max-frames 1800 --person-selection-mode "most_motion" --disable-structured-storage --reference-capture-mode "best_window" --ref-min-motion-energy 0.02 --ref-min-score-gate 0

# 38. spinning_back_kick__left45
& "python" "action_recognition.py" --weights "yolo26n-pose.pt" --source "https://www.youtube.com/watch?v=BDORUMu__is" --record-reference "spinning_back_kick__left45" --target-technique "spinning_back_kick" --reference-dir "reference_poses" --num-video-sequence-samples 12 --skip-frame 1 --save-kpts-dir "keypoints" --record-reference-max-saves 1 --reference-capture-cooldown-frames 24 --disable-video-classifier --visualize-pose --auto-exit-after-reference --reference-search-max-frames 1800 --person-selection-mode "most_motion" --disable-structured-storage --reference-capture-mode "best_window" --ref-min-motion-energy 0.02 --ref-min-score-gate 0

# 39. spinning_back_kick__right45
& "python" "action_recognition.py" --weights "yolo26n-pose.pt" --source "https://www.youtube.com/watch?v=IuQeTww3c3o" --record-reference "spinning_back_kick__right45" --target-technique "spinning_back_kick" --reference-dir "reference_poses" --num-video-sequence-samples 12 --skip-frame 1 --save-kpts-dir "keypoints" --record-reference-max-saves 1 --reference-capture-cooldown-frames 24 --disable-video-classifier --visualize-pose --auto-exit-after-reference --reference-search-max-frames 1800 --person-selection-mode "most_motion" --disable-structured-storage --reference-capture-mode "best_window" --ref-min-motion-energy 0.02 --ref-min-score-gate 0

# 40. spinning_back_kick__side
& "python" "action_recognition.py" --weights "yolo26n-pose.pt" --source "https://www.youtube.com/watch?v=uTuugDIWjNQ" --record-reference "spinning_back_kick__side" --target-technique "spinning_back_kick" --reference-dir "reference_poses" --num-video-sequence-samples 12 --skip-frame 1 --save-kpts-dir "keypoints" --record-reference-max-saves 1 --reference-capture-cooldown-frames 24 --disable-video-classifier --visualize-pose --auto-exit-after-reference --reference-search-max-frames 1800 --person-selection-mode "most_motion" --disable-structured-storage --reference-capture-mode "best_window" --ref-min-motion-energy 0.02 --ref-min-score-gate 0

# 41. knee_strike__front
& "python" "action_recognition.py" --weights "yolo26n-pose.pt" --source "https://www.youtube.com/watch?v=XzXUM6i9Qdw" --record-reference "knee_strike__front" --target-technique "knee_strike" --reference-dir "reference_poses" --num-video-sequence-samples 12 --skip-frame 1 --save-kpts-dir "keypoints" --record-reference-max-saves 1 --reference-capture-cooldown-frames 24 --disable-video-classifier --visualize-pose --auto-exit-after-reference --reference-search-max-frames 1800 --person-selection-mode "most_motion" --disable-structured-storage --reference-capture-mode "best_window" --ref-min-motion-energy 0.02 --ref-min-score-gate 0

# 42. knee_strike__left45
& "python" "action_recognition.py" --weights "yolo26n-pose.pt" --source "https://www.youtube.com/watch?v=pPmnlFqhRfw" --record-reference "knee_strike__left45" --target-technique "knee_strike" --reference-dir "reference_poses" --num-video-sequence-samples 12 --skip-frame 1 --save-kpts-dir "keypoints" --record-reference-max-saves 1 --reference-capture-cooldown-frames 24 --disable-video-classifier --visualize-pose --auto-exit-after-reference --reference-search-max-frames 1800 --person-selection-mode "most_motion" --disable-structured-storage --reference-capture-mode "best_window" --ref-min-motion-energy 0.02 --ref-min-score-gate 0

# 43. knee_strike__right45
& "python" "action_recognition.py" --weights "yolo26n-pose.pt" --source "https://www.youtube.com/watch?v=0ZlSlVtm-7Y" --record-reference "knee_strike__right45" --target-technique "knee_strike" --reference-dir "reference_poses" --num-video-sequence-samples 12 --skip-frame 1 --save-kpts-dir "keypoints" --record-reference-max-saves 1 --reference-capture-cooldown-frames 24 --disable-video-classifier --visualize-pose --auto-exit-after-reference --reference-search-max-frames 1800 --person-selection-mode "most_motion" --disable-structured-storage --reference-capture-mode "best_window" --ref-min-motion-energy 0.02 --ref-min-score-gate 0

# 44. knee_strike__side
& "python" "action_recognition.py" --weights "yolo26n-pose.pt" --source "https://www.youtube.com/watch?v=SD2PvP-jVds" --record-reference "knee_strike__side" --target-technique "knee_strike" --reference-dir "reference_poses" --num-video-sequence-samples 12 --skip-frame 1 --save-kpts-dir "keypoints" --record-reference-max-saves 1 --reference-capture-cooldown-frames 24 --disable-video-classifier --visualize-pose --auto-exit-after-reference --reference-search-max-frames 1800 --person-selection-mode "most_motion" --disable-structured-storage --reference-capture-mode "best_window" --ref-min-motion-energy 0.02 --ref-min-score-gate 0

# 45. elbow_strike__front
& "python" "action_recognition.py" --weights "yolo26n-pose.pt" --source "https://www.youtube.com/watch?v=fVeGKwcp700" --record-reference "elbow_strike__front" --target-technique "elbow_strike" --reference-dir "reference_poses" --num-video-sequence-samples 12 --skip-frame 1 --save-kpts-dir "keypoints" --record-reference-max-saves 1 --reference-capture-cooldown-frames 24 --disable-video-classifier --visualize-pose --auto-exit-after-reference --reference-search-max-frames 1800 --person-selection-mode "most_motion" --disable-structured-storage --reference-capture-mode "best_window" --ref-min-motion-energy 0.02 --ref-min-score-gate 0

# 46. elbow_strike__left45
& "python" "action_recognition.py" --weights "yolo26n-pose.pt" --source "https://www.youtube.com/watch?v=mp771sLeuQs" --record-reference "elbow_strike__left45" --target-technique "elbow_strike" --reference-dir "reference_poses" --num-video-sequence-samples 12 --skip-frame 1 --save-kpts-dir "keypoints" --record-reference-max-saves 1 --reference-capture-cooldown-frames 24 --disable-video-classifier --visualize-pose --auto-exit-after-reference --reference-search-max-frames 1800 --person-selection-mode "most_motion" --disable-structured-storage --reference-capture-mode "best_window" --ref-min-motion-energy 0.02 --ref-min-score-gate 0

# 47. elbow_strike__right45
& "python" "action_recognition.py" --weights "yolo26n-pose.pt" --source "https://www.youtube.com/watch?v=Q0vhmmAhWfA" --record-reference "elbow_strike__right45" --target-technique "elbow_strike" --reference-dir "reference_poses" --num-video-sequence-samples 12 --skip-frame 1 --save-kpts-dir "keypoints" --record-reference-max-saves 1 --reference-capture-cooldown-frames 24 --disable-video-classifier --visualize-pose --auto-exit-after-reference --reference-search-max-frames 1800 --person-selection-mode "most_motion" --disable-structured-storage --reference-capture-mode "best_window" --ref-min-motion-energy 0.02 --ref-min-score-gate 0

# 48. elbow_strike__side
& "python" "action_recognition.py" --weights "yolo26n-pose.pt" --source "https://www.youtube.com/watch?v=b2EaxgTDWZc" --record-reference "elbow_strike__side" --target-technique "elbow_strike" --reference-dir "reference_poses" --num-video-sequence-samples 12 --skip-frame 1 --save-kpts-dir "keypoints" --record-reference-max-saves 1 --reference-capture-cooldown-frames 24 --disable-video-classifier --visualize-pose --auto-exit-after-reference --reference-search-max-frames 1800 --person-selection-mode "most_motion" --disable-structured-storage --reference-capture-mode "best_window" --ref-min-motion-energy 0.02 --ref-min-score-gate 0

# 49. axe_kick__front
& "python" "action_recognition.py" --weights "yolo26n-pose.pt" --source "https://www.youtube.com/watch?v=4IvPiUtUsSE" --record-reference "axe_kick__front" --target-technique "axe_kick" --reference-dir "reference_poses" --num-video-sequence-samples 12 --skip-frame 1 --save-kpts-dir "keypoints" --record-reference-max-saves 1 --reference-capture-cooldown-frames 24 --disable-video-classifier --visualize-pose --auto-exit-after-reference --reference-search-max-frames 1800 --person-selection-mode "most_motion" --disable-structured-storage --reference-capture-mode "best_window" --ref-min-motion-energy 0.02 --ref-min-score-gate 0

# 50. axe_kick__left45
& "python" "action_recognition.py" --weights "yolo26n-pose.pt" --source "https://www.youtube.com/watch?v=jmZgJXwHNQY" --record-reference "axe_kick__left45" --target-technique "axe_kick" --reference-dir "reference_poses" --num-video-sequence-samples 12 --skip-frame 1 --save-kpts-dir "keypoints" --record-reference-max-saves 1 --reference-capture-cooldown-frames 24 --disable-video-classifier --visualize-pose --auto-exit-after-reference --reference-search-max-frames 1800 --person-selection-mode "most_motion" --disable-structured-storage --reference-capture-mode "best_window" --ref-min-motion-energy 0.02 --ref-min-score-gate 0

# 51. axe_kick__right45
& "python" "action_recognition.py" --weights "yolo26n-pose.pt" --source "https://www.youtube.com/watch?v=Vnmv0OtqnGI" --record-reference "axe_kick__right45" --target-technique "axe_kick" --reference-dir "reference_poses" --num-video-sequence-samples 12 --skip-frame 1 --save-kpts-dir "keypoints" --record-reference-max-saves 1 --reference-capture-cooldown-frames 24 --disable-video-classifier --visualize-pose --auto-exit-after-reference --reference-search-max-frames 1800 --person-selection-mode "most_motion" --disable-structured-storage --reference-capture-mode "best_window" --ref-min-motion-energy 0.02 --ref-min-score-gate 0

# 52. axe_kick__side
& "python" "action_recognition.py" --weights "yolo26n-pose.pt" --source "https://www.youtube.com/watch?v=1OoNhh-Cr-I" --record-reference "axe_kick__side" --target-technique "axe_kick" --reference-dir "reference_poses" --num-video-sequence-samples 12 --skip-frame 1 --save-kpts-dir "keypoints" --record-reference-max-saves 1 --reference-capture-cooldown-frames 24 --disable-video-classifier --visualize-pose --auto-exit-after-reference --reference-search-max-frames 1800 --person-selection-mode "most_motion" --disable-structured-storage --reference-capture-mode "best_window" --ref-min-motion-energy 0.02 --ref-min-score-gate 0
