from __future__ import annotations

import argparse
import csv
import json
import math
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path


SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent


def _resolve_project_path(path_value: str) -> Path:
    p = Path(path_value)
    return p if p.is_absolute() else PROJECT_ROOT / p


def _as_float(value: str, default: float = float("nan")) -> float:
    try:
        return float(value)
    except (TypeError, ValueError):
        return default


def _as_int(value: str, default: int = -1) -> int:
    try:
        return int(float(value))
    except (TypeError, ValueError):
        return default


@dataclass
class MetricRow:
    frame: int
    score_100: float
    score_threshold_100: float
    run_id: str
    technique: str
    track_id: str


def _load_metrics(metrics_csv: Path) -> list[MetricRow]:
    rows: list[MetricRow] = []
    with metrics_csv.open("r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        for r in reader:
            frame = _as_int(r.get("frame", ""), -1)
            score = _as_float(r.get("score", ""))
            threshold = _as_float(r.get("score_threshold", ""), 70.0)
            if frame < 0 or not math.isfinite(score):
                continue
            rows.append(
                MetricRow(
                    frame=frame,
                    score_100=score,
                    score_threshold_100=threshold,
                    run_id=(r.get("run_id", "") or "").strip(),
                    technique=(r.get("technique", "") or "").strip(),
                    track_id=(r.get("track_id", "") or "").strip(),
                )
            )
    return rows


def _pearson(x: list[float], y: list[float]) -> float:
    if len(x) != len(y) or len(x) < 2:
        return float("nan")
    mx = sum(x) / len(x)
    my = sum(y) / len(y)
    num = sum((a - mx) * (b - my) for a, b in zip(x, y))
    den_x = math.sqrt(sum((a - mx) ** 2 for a in x))
    den_y = math.sqrt(sum((b - my) ** 2 for b in y))
    den = den_x * den_y
    if den <= 1e-12:
        return float("nan")
    return num / den


def _nearest_metric_row(
    rows: list[MetricRow],
    target_frame: int,
    max_frame_gap: int,
    technique: str,
    track_id: str,
) -> tuple[MetricRow | None, int]:
    candidates = rows
    if technique:
        candidates = [r for r in candidates if r.technique == technique]
    if track_id:
        candidates = [r for r in candidates if r.track_id == track_id]
    if not candidates:
        return None, -1

    best = min(candidates, key=lambda r: abs(r.frame - target_frame))
    gap = abs(best.frame - target_frame)
    if gap > max_frame_gap:
        return None, gap
    return best, gap


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Match expert oral scores (1-10) to trainer metrics rows and compute agreement statistics. "
            "Expert CSV columns: frame,expert_score_1_10[,sample_id,technique,track_id,notes]"
        )
    )
    parser.add_argument(
        "--metrics-csv",
        type=str,
        required=True,
        help="path to run metrics.csv generated by action_recognition.py",
    )
    parser.add_argument(
        "--expert-csv",
        type=str,
        required=True,
        help="CSV with oral expert labels (1-10)",
    )
    parser.add_argument(
        "--output-csv",
        type=str,
        default="data/runs/oral_eval_matches.csv",
        help="matched sample-level output CSV",
    )
    parser.add_argument(
        "--summary-json",
        type=str,
        default="data/runs/oral_eval_summary.json",
        help="summary statistics JSON",
    )
    parser.add_argument(
        "--max-frame-gap",
        type=int,
        default=20,
        help="maximum allowed frame difference when matching expert row to metrics row",
    )
    parser.add_argument(
        "--expert-pass-threshold",
        type=float,
        default=7.0,
        help="threshold on 1-10 expert scale used for pass/fail agreement",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()

    metrics_csv = _resolve_project_path(args.metrics_csv)
    expert_csv = _resolve_project_path(args.expert_csv)
    output_csv = _resolve_project_path(args.output_csv)
    summary_json = _resolve_project_path(args.summary_json)

    if not metrics_csv.exists():
        print(f"error: metrics CSV not found: {metrics_csv}")
        return 2
    if not expert_csv.exists():
        print(f"error: expert CSV not found: {expert_csv}")
        return 2

    metric_rows = _load_metrics(metrics_csv)
    if not metric_rows:
        print("error: no valid rows found in metrics CSV")
        return 1

    matched: list[dict[str, str | int | float]] = []
    with expert_csv.open("r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        for idx, row in enumerate(reader, start=1):
            frame = _as_int(row.get("frame", ""), -1)
            expert_score = _as_float(row.get("expert_score_1_10", ""))
            if frame < 0 or not math.isfinite(expert_score):
                continue

            sample_id = (row.get("sample_id", "") or f"sample_{idx}").strip()
            technique = (row.get("technique", "") or "").strip()
            track_id = (row.get("track_id", "") or "").strip()

            best, gap = _nearest_metric_row(
                rows=metric_rows,
                target_frame=frame,
                max_frame_gap=max(args.max_frame_gap, 0),
                technique=technique,
                track_id=track_id,
            )
            if best is None:
                continue

            program_score_10 = best.score_100 / 10.0
            abs_diff = abs(expert_score - program_score_10)
            sq_diff = abs_diff * abs_diff
            program_pass_threshold_10 = best.score_threshold_100 / 10.0
            expert_pass = expert_score >= float(args.expert_pass_threshold)
            program_pass = program_score_10 >= program_pass_threshold_10

            matched.append(
                {
                    "sample_id": sample_id,
                    "expert_frame": frame,
                    "matched_frame": best.frame,
                    "frame_gap": gap,
                    "technique": best.technique,
                    "track_id": best.track_id,
                    "expert_score_1_10": round(expert_score, 4),
                    "program_score_1_10": round(program_score_10, 4),
                    "program_score_0_100": round(best.score_100, 4),
                    "program_threshold_1_10": round(program_pass_threshold_10, 4),
                    "expert_pass": expert_pass,
                    "program_pass": program_pass,
                    "abs_diff": round(abs_diff, 4),
                    "sq_diff": round(sq_diff, 6),
                    "notes": (row.get("notes", "") or "").strip(),
                }
            )

    if not matched:
        print("no matched rows. Check frame indices and --max-frame-gap.")
        return 1

    expert_scores = [float(r["expert_score_1_10"]) for r in matched]
    program_scores = [float(r["program_score_1_10"]) for r in matched]
    abs_diffs = [float(r["abs_diff"]) for r in matched]
    sq_diffs = [float(r["sq_diff"]) for r in matched]

    mae = sum(abs_diffs) / len(abs_diffs)
    rmse = math.sqrt(sum(sq_diffs) / len(sq_diffs))
    pearson = _pearson(expert_scores, program_scores)
    pass_agreement = sum(1 for r in matched if bool(r["expert_pass"]) == bool(r["program_pass"])) / len(matched)

    output_csv.parent.mkdir(parents=True, exist_ok=True)
    summary_json.parent.mkdir(parents=True, exist_ok=True)

    fieldnames = [
        "sample_id",
        "expert_frame",
        "matched_frame",
        "frame_gap",
        "technique",
        "track_id",
        "expert_score_1_10",
        "program_score_1_10",
        "program_score_0_100",
        "program_threshold_1_10",
        "expert_pass",
        "program_pass",
        "abs_diff",
        "sq_diff",
        "notes",
    ]

    with output_csv.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(matched)

    summary_payload = {
        "created_at": datetime.now(timezone.utc).isoformat(),
        "metrics_csv": str(metrics_csv),
        "expert_csv": str(expert_csv),
        "output_csv": str(output_csv),
        "n_samples": len(matched),
        "mae": mae,
        "rmse": rmse,
        "pearson_r": pearson,
        "pass_agreement": pass_agreement,
        "expert_pass_threshold_1_10": float(args.expert_pass_threshold),
        "max_frame_gap": int(args.max_frame_gap),
    }

    summary_json.write_text(json.dumps(summary_payload, indent=2), encoding="utf-8")

    print(f"matched samples: {len(matched)}")
    print(f"MAE: {mae:.4f}")
    print(f"RMSE: {rmse:.4f}")
    print(f"Pearson r: {pearson:.4f}" if math.isfinite(pearson) else "Pearson r: nan")
    print(f"Pass agreement: {pass_agreement * 100.0:.2f}%")
    print(f"written: {output_csv}")
    print(f"written: {summary_json}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
